In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.feature_selection import SequentialFeatureSelector



def fwdselection(indep_X,dep_Y,n):
        #bwdlist=[]
        
        from sklearn.linear_model import LinearRegression
        lin = LinearRegression()
        
        #from sklearn.svm import SVR
        #SVRl = SVR(kernel = 'linear')
        
        #from sklearn.svm import SVR
        #SVRnl = SVR(kernel = 'rbf')
        
        #from sklearn.tree import DecisionTreeRegressor
        #dec = DecisionTreeRegressor(random_state = 0)
        
        #from sklearn.ensemble import RandomForestRegressor
        #rf = RandomForestRegressor(n_estimators = 5, random_state = 0)
         #rfemodellist=[lin,dec,rf] 
        #for i in   rfemodellist:
            #print(i)
        sfs1= SequentialFeatureSelector(lin,n_features_to_select=n,direction='backward',scoring='accuracy')
        sfsfit=sfs1.fit(indep_X,dep_Y)
        featurename= sfsfit.get_support(indices=True)
        selected_features=df2.columns[featurename]
        #Converting index panads to alist
        features=selected_features.to_list()
        # summarize scores       
        print("The features are",features)
        sfs_feature=sfsfit.transform(indep_X)
            #bwdlist.append(sfs_feature)
        return sfs_feature
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2
 
def Linear(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2   
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training setC
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def random(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2 
    
    
def sfs_Regression(acclin,accdt,accrf): 
    
    sfsdataframe=pd.DataFrame(index=['Logistic','DecisionTree','Random'],columns=['Linear','Decision','Random'])
    for number,idex in enumerate(sfsdataframe.index):      
        sfsdataframe['Linear'][idex]=acclin[number]       
        sfsdataframe['Decision'][idex]=accdt[number]
        sfsdataframe['Random'][idex]=accrf[number]
    return sfsdataframe

In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2,dtype=int,drop_first=True)

indep_X=df2.drop('classification_yes',axis= 1)
dep_Y=df2['classification_yes']

In [3]:
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [11]:
sfs_feature=fwdselection(indep_X,dep_Y,3)
sfs_feature

The features are ['appet_yes', 'pe_yes', 'ane_yes']

array([[1., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 0., 0.]])

In [12]:
sfs_feature.shape

(399, 3)

In [13]:
acclin=[]
accdt=[]
accrf=[]

In [14]:
X_train, X_test, y_train, y_test=split_scalar(sfs_feature,dep_Y)  
r2_lin=Linear(X_train,y_train,X_test)
acclin.append(r2_lin)

#r2_sl=svm_linear(X_train,y_train,X_test)    
#accsvml.append(r2_sl)

#r2_NL=svm_NL(X_train,y_train,X_test)
#accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test)
accdt.append(r2_d)

r2_r=random(X_train,y_train,X_test)
accrf.append(r2_r)

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [15]:
sfsdataframe=pd.DataFrame(index=['Linear'],columns=['Linear','Decision','Random'])
for number,idex in enumerate(sfsdataframe.index):      
    sfsdataframe['Linear'][idex]=acclin[number]       
    sfsdataframe['Decision'][idex]=accdt[number]
    sfsdataframe['Random'][idex]=accrf[number]

In [10]:
#result 10
sfsdataframe

          Linear  Decision   Random
Linear  0.416888  0.604407  0.56734

In [16]:
#result 3
sfsdataframe

          Linear  Decision    Random
Linear  0.211729  0.283129  0.282748